"""Initial tenant schema

Revision ID: fcf867a39753
Revises: 04a28785668a
Create Date: 2026-07-18 09:57:22.199083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf867a39753'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    import os
    if os.environ.get("ALEMBIC_MODE") == "public":
        return
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy.dialects.postgresql import ENUM
    op.create_table('buyers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('type', ENUM('COMMERCIAL', 'DOMESTIC', name='buyertype', schema='public', create_type=False), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('balance_pending', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cylinders_pending', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyers')),
    schema='tenant'
    )
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', ENUM('COMMERCIAL', 'DOMESTIC', 'RETAIL', name='itemcategory', schema='public', create_type=False), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('initial_full', sa.Integer(), nullable=False),
    sa.Column('initial_empty', sa.Integer(), nullable=False),
    sa.Column('current_full', sa.Integer(), nullable=False),
    sa.Column('current_empty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    schema='tenant'
    )
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('balance_pending', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cylinders_pending', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    schema='tenant'
    )
    op.create_table('purchase_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('full_received', sa.Integer(), nullable=False),
    sa.Column('empty_returned', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['tenant.items.id'], name=op.f('fk_purchase_entries_item_id_items')),
    sa.ForeignKeyConstraint(['provider_id'], ['tenant.providers.id'], name=op.f('fk_purchase_entries_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_entries')),
    schema='tenant'
    )
    op.create_table('delivery_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=True),
    sa.Column('adhoc_buyer_name', sa.String(length=255), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('unit_price_at_delivery', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_bill_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('full_delivered', sa.Integer(), nullable=False),
    sa.Column('empty_received', sa.Integer(), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('upi_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['tenant.buyers.id'], name=op.f('fk_delivery_entries_buyer_id_buyers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_delivery_entries_driver_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['tenant.items.id'], name=op.f('fk_delivery_entries_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_entries')),
    schema='tenant'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_entries', schema='tenant')
    op.drop_table('purchase_entries', schema='tenant')
    op.drop_table('providers', schema='tenant')
    op.drop_table('items', schema='tenant')
    op.drop_table('buyers', schema='tenant')
    # ### end Alembic commands ###
