"""Initial schema-per-tenant layout

Revision ID: 14e5c5f3f259
Revises: 
Create Date: 2026-07-14 15:20:26.879063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14e5c5f3f259'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('buyers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('type', sa.Enum('COMMERCIAL', 'DOMESTIC', name='buyertype'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('balance_pending', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cylinders_pending', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_buyers')),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_buyers_id'), 'buyers', ['id'], unique=False, schema='tenant')
    op.create_table('items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.Enum('COMMERCIAL', 'DOMESTIC', 'RETAIL', name='itemcategory'), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('initial_full', sa.Integer(), nullable=False),
    sa.Column('initial_empty', sa.Integer(), nullable=False),
    sa.Column('current_full', sa.Integer(), nullable=False),
    sa.Column('current_empty', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_items')),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_items_id'), 'items', ['id'], unique=False, schema='tenant')
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'TENANT_ADMIN', 'DRIVER', name='userrole'), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('ix_users_org_role_active', 'users', ['organization_id', 'role', 'is_active'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index('uq_users_org_username', 'users', [sa.literal_column('lower(username)'), 'organization_id'], unique=True, postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))
    op.create_index('uq_users_platform_username', 'users', [sa.literal_column('lower(username)')], unique=True, postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
    op.create_table('delivery_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('driver_id', sa.Uuid(), nullable=False),
    sa.Column('buyer_id', sa.Uuid(), nullable=True),
    sa.Column('adhoc_buyer_name', sa.String(length=255), nullable=True),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('unit_price_at_delivery', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_bill_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('full_delivered', sa.Integer(), nullable=False),
    sa.Column('empty_received', sa.Integer(), nullable=False),
    sa.Column('cash_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('upi_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['tenant.buyers.id'], name=op.f('fk_delivery_entries_buyer_id_buyers'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_delivery_entries_driver_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['tenant.items.id'], name=op.f('fk_delivery_entries_item_id_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_delivery_entries')),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_delivery_entries_buyer_id'), 'delivery_entries', ['buyer_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_delivery_entries_driver_id'), 'delivery_entries', ['driver_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_delivery_entries_id'), 'delivery_entries', ['id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_delivery_entries_idempotency_key'), 'delivery_entries', ['idempotency_key'], unique=True, schema='tenant')
    op.create_index(op.f('ix_tenant_delivery_entries_item_id'), 'delivery_entries', ['item_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_delivery_entries_item_id'), table_name='delivery_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_delivery_entries_idempotency_key'), table_name='delivery_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_delivery_entries_id'), table_name='delivery_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_delivery_entries_driver_id'), table_name='delivery_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_delivery_entries_buyer_id'), table_name='delivery_entries', schema='tenant')
    op.drop_table('delivery_entries', schema='tenant')
    op.drop_index('uq_users_platform_username', table_name='users', postgresql_where=sa.text('organization_id IS NULL'), sqlite_where=sa.text('organization_id IS NULL'))
    op.drop_index('uq_users_org_username', table_name='users', postgresql_where=sa.text('organization_id IS NOT NULL'), sqlite_where=sa.text('organization_id IS NOT NULL'))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index('ix_users_org_role_active', table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenant_items_id'), table_name='items', schema='tenant')
    op.drop_table('items', schema='tenant')
    op.drop_index(op.f('ix_tenant_buyers_id'), table_name='buyers', schema='tenant')
    op.drop_table('buyers', schema='tenant')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
