"""Add capacity_kg and price_per_kg

Revision ID: 5da4a5a87f0f
Revises: d523fd0c13b6
Create Date: 2026-07-16 13:06:58.782364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da4a5a87f0f'
down_revision: Union[str, Sequence[str], None] = 'd523fd0c13b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buyers', sa.Column('price_per_kg', sa.Numeric(precision=10, scale=2), nullable=True), schema='tenant')
    op.add_column('items', sa.Column('capacity_kg', sa.Numeric(precision=10, scale=2), nullable=True), schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'capacity_kg', schema='tenant')
    op.drop_column('buyers', 'price_per_kg', schema='tenant')
    # ### end Alembic commands ###
