"""make username globally unique

Revision ID: 5fb66b61bb08
Revises: 5da4a5a87f0f
Create Date: 2026-07-17 19:25:46.199354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb66b61bb08'
down_revision: Union[str, Sequence[str], None] = '5da4a5a87f0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Dedup existing usernames by appending org_id to duplicates
    op.execute("""
        UPDATE users 
        SET username = username || '_' || organization_id
        WHERE id IN (
            SELECT id FROM (
                SELECT id, ROW_NUMBER() OVER (
                    PARTITION BY LOWER(username) ORDER BY created_at ASC
                ) as rnum 
                FROM users
            ) t WHERE t.rnum > 1
        );
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('uq_users_org_username'), table_name='users', postgresql_where='(organization_id IS NOT NULL)')
    op.drop_index(op.f('uq_users_platform_username'), table_name='users', postgresql_where='(organization_id IS NULL)')
    op.create_index('uq_users_username', 'users', [sa.literal_column('lower(username)')], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_users_username', table_name='users')
    op.create_index(op.f('uq_users_platform_username'), 'users', [sa.literal_column('lower(username::text)')], unique=True, postgresql_where='(organization_id IS NULL)')
    op.create_index(op.f('uq_users_org_username'), 'users', [sa.literal_column('lower(username::text)'), 'organization_id'], unique=True, postgresql_where='(organization_id IS NOT NULL)')
    # ### end Alembic commands ###
