"""Add providers and purchase entries

Revision ID: cc93f82404ce
Revises: 14e5c5f3f259
Create Date: 2026-07-14 16:39:57.507293

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc93f82404ce'
down_revision: Union[str, Sequence[str], None] = '14e5c5f3f259'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('balance_pending', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cylinders_pending', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_providers')),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_providers_id'), 'providers', ['id'], unique=False, schema='tenant')
    op.create_table('purchase_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('item_id', sa.Uuid(), nullable=False),
    sa.Column('full_received', sa.Integer(), nullable=False),
    sa.Column('empty_returned', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['tenant.items.id'], name=op.f('fk_purchase_entries_item_id_items')),
    sa.ForeignKeyConstraint(['provider_id'], ['tenant.providers.id'], name=op.f('fk_purchase_entries_provider_id_providers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_purchase_entries')),
    schema='tenant'
    )
    op.create_index(op.f('ix_tenant_purchase_entries_id'), 'purchase_entries', ['id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_purchase_entries_item_id'), 'purchase_entries', ['item_id'], unique=False, schema='tenant')
    op.create_index(op.f('ix_tenant_purchase_entries_provider_id'), 'purchase_entries', ['provider_id'], unique=False, schema='tenant')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_purchase_entries_provider_id'), table_name='purchase_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_purchase_entries_item_id'), table_name='purchase_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_purchase_entries_id'), table_name='purchase_entries', schema='tenant')
    op.drop_table('purchase_entries', schema='tenant')
    op.drop_index(op.f('ix_tenant_providers_id'), table_name='providers', schema='tenant')
    op.drop_table('providers', schema='tenant')
    # ### end Alembic commands ###
