"""Add max_users to organizations

Revision ID: d523fd0c13b6
Revises: cc93f82404ce
Create Date: 2026-07-15 11:04:58.413068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd523fd0c13b6'
down_revision: Union[str, Sequence[str], None] = 'cc93f82404ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('max_users', sa.Integer(), nullable=False, server_default='10'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'max_users')
    # ### end Alembic commands ###
