"""cascade_delete_users

Revision ID: b235c2b39a61
Revises: 04a28785668a
Create Date: 2026-07-18 10:39:29.223815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b235c2b39a61'
down_revision: Union[str, Sequence[str], None] = '04a28785668a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


import os

def upgrade() -> None:
    """Upgrade schema."""
    if os.environ.get("ALEMBIC_MODE") == "tenant":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_organization_id_organizations'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_organization_id_organizations'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    if os.environ.get("ALEMBIC_MODE") == "tenant":
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_organization_id_organizations'), 'users', type_='foreignkey')
    op.create_foreign_key(op.f('fk_users_organization_id_organizations'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
